### ISSUE TITLE
Failed to compile ssimulacra2-cuda-kernel v0.1.0 on Windows 10

### ISSUE THREAD

**Issue by Ironclad17** [Gui-Yom/turbo-metrics#2]
Just installed cuda 12.6 (NPP included) and NVIDIA Video Codec SDK, added environmental variables, ran rustup nightly updates.
`cargo build --release -p turbo-metrics` failed with the following error:
```
error: failed to run custom build command for `ssimulacra2-cuda v0.1.0 (C:\Users\*\repos\turbo-metrics\crates\ssimulacra2-cuda)`

Caused by:
  process didn't exit successfully: `C:\Users\*\repos\turbo-metrics\target\release\build\ssimulacra2-cuda-0824a1eecf5122e7\build-script-build` (exit code: 101)
  --- stdout
  cargo::rerun-if-changed=C:\Users\*\repos\turbo-metrics\crates\ssimulacra2-cuda-kernel\Cargo.toml
  cargo::rerun-if-changed=C:\Users\*\repos\turbo-metrics\crates\ssimulacra2-cuda-kernel\src
  cargo::rerun-if-changed=C:\Users\*\repos\turbo-metrics\crates\ssimulacra2-cuda-kernel\build.rs

  --- stderr
      Blocking waiting for file lock on package cache
      Blocking waiting for file lock on build directory
     Compiling autocfg v1.4.0
     Compiling bytemuck v1.18.0
     Compiling paste v1.0.15
     Compiling typenum v1.17.0
     Compiling rawpointer v0.2.1
  warning: unused import: `crate::panic::*`
    --> crates\nvptx-core\src\lib.rs:15:13
     |
  15 |     pub use crate::panic::*;
     |             ^^^^^^^^^^^^^^^
     |
     = note: `#[warn(unused_imports)]` on by default

  warning: `nvptx-core` (lib) generated 1 warning (run `cargo fix --lib -p nvptx-core` to apply 1 suggestion)
     Compiling safe_arch v0.7.2
     Compiling num-traits v0.2.19
     Compiling matrixmultiply v0.3.9
     Compiling wide v0.7.28
     Compiling num-integer v0.1.46
     Compiling num-complex v0.4.6
     Compiling approx v0.5.1
     Compiling num-rational v0.4.2
     Compiling simba v0.9.0
     Compiling nalgebra v0.33.0
     Compiling ssimulacra2-cuda-kernel v0.1.0 (C:\Users\*\repos\turbo-metrics\crates\ssimulacra2-cuda-kernel)
  error: failed to run custom build command for `ssimulacra2-cuda-kernel v0.1.0 (C:\Users\*\repos\turbo-metrics\crates\ssimulacra2-cuda-kernel)`

  Caused by:
    process didn't exit successfully: `C:\Users\*\repos\turbo-metrics\target\release-nvptx\build\ssimulacra2-cuda-kernel-cb1caf1ee4ae6f53\build-script-build` (exit code: 101)
    --- stdout
    cargo:rerun-if-env-changed=CUDA_PATH
    cargo:rustc-link-arg=C:\Program Files\NVIDIA Corporation\CUDA/nvvm/libdevice/libdevice.10.bc
    cargo:rerun-if-changed=C:\Users\*\repos\turbo-metrics\crates\ssimulacra2-cuda-kernel/shared.bc

    --- stderr
    thread 'main' panicked at crates\ssimulacra2-cuda-kernel\build.rs:23:10:
    called `Result::unwrap()` on an `Err` value: Error { kind: NotFound, message: "program not found" }
    note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
  thread 'main' panicked at crates\nvptx-builder\src\lib.rs:61:5:
  assertion failed: cmd.wait().unwrap().success()
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace```

**Comment by Gui-Yom** [comment]
This looks like one of the problems outlined in #1, and should be fixed with the latest commits.

For reference, this was caused by `llvm-as` not being found as llvm-tools are not present in path. On my machine this did not fail because I had a complete llvm distribution in path. With the fix, the build script explicitly resolve to the binary present in the rustlib.

**Comment by Gui-Yom** [comment]
@Ironclad17 hey, is the issue fixed on your side ?

**Comment by Ironclad17** [comment]
Yes it did thank you!
